### ISSUE TITLE
Create Doctor Login Page

### ISSUE THREAD

**Issue by Shreesh90** [Shreesh90/RAaS-IIT2019044#2]

**Comment by Shreesh90** [comment]
![image](https://user-images.githubusercontent.com/6941016/107638194-3f213580-6c95-11eb-805b-ecca5396f42f.png)
Edit such that the login bars and images are at the middle of the screen height wise

**Comment by Shreesh90** [comment]
![image](https://user-images.githubusercontent.com/6941016/107638406-8dcecf80-6c95-11eb-95fc-16ed0eddec08.png)
Tackle this issue of mobile/tablet view

**Comment by Ayan0904** [comment]
![ss1](https://user-images.githubusercontent.com/72779637/111585793-13560b80-877d-11eb-8ff7-ad600097014e.png)
![ss2](https://user-images.githubusercontent.com/72779637/111585799-151fcf00-877d-11eb-8796-40e7c6592cfa.png)
Done
